// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyqdH-LMbCb1YPyPDskWlVMXal7vHFA6o',
    appId: '1:256752383946:web:1820f4b2730b71e302c133',
    messagingSenderId: '256752383946',
    projectId: 'kitkatsocialapp',
    authDomain: 'kitkatsocialapp.firebaseapp.com',
    storageBucket: 'kitkatsocialapp.firebasestorage.app',
    measurementId: 'G-T6006P24DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDMXwn5rKEdJg_N2cSfjdnL8h2Q_-jDvU',
    appId: '1:256752383946:android:67a75a6270c8b6c102c133',
    messagingSenderId: '256752383946',
    projectId: 'kitkatsocialapp',
    storageBucket: 'kitkatsocialapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkVjRnBc-SdJehsgjnZSCUNo-WpfEJDBE',
    appId: '1:256752383946:ios:522f5eda5035991c02c133',
    messagingSenderId: '256752383946',
    projectId: 'kitkatsocialapp',
    storageBucket: 'kitkatsocialapp.firebasestorage.app',
    iosBundleId: 'kit.kat.final.exam.kitkatSocialApp',
  );
}
